#!/usr/bin/env node

var fs = require('fs');
var proc = require('child_process');

function json_value(path, value) { return JSON.parse(fs.readFileSync(path).toString())[value]; };

var modulePath = './node_modules';
var packagerCmd = modulePath + '/.bin/electron-packager';
var prebuiltPath = modulePath + '/electron-prebuilt';
var prebuiltPkgPath = prebuiltPath + '/package.json';
var buildOutputPath = './release';
var compileCmd = './script/compile';

var ignorePaths='node_modules/electron-compile/node_modules/electron-compilers|node_modules/\\.bin|node_modules/electron-rebuild|node_modules/electron-jasmine|(/release$)|(/script$)|(/spec$)';

var electronVersion = json_value(prebuiltPkgPath, 'version');
var appName = json_value('package.json', 'appName');

proc.spawnSync(compileCmd, [], {stdio: 'inherit'});

console.log('Building ' + appName);

var defaultArgs = ['./', appName, '--overwrite', '--platform', process.platform, '--arch', process.arch, '--version', electronVersion, '--ignore', ignorePaths, '--out', buildOutputPath];
var args = defaultArgs.concat(process.argv.splice(2));

proc.spawn(packagerCmd, args, {stdio: 'inherit'});
